export default [
    { id: 1, name: "Docker"},
    { id: 2, name: "PHP" },
    { id: 3, name: "HTML"},
    { id: 4, name: "CSS"},
    { id: 5, name: "Javascript"},
    { id: 6, name: "REST API" },
    { id: 7, name: "HTTP" },
    { id: 8, name: "JSON" },
    { id: 9, name: "Git" },
    { id: 10, name: "Version Control" },
    { id: 11, name: "GitHub" },
    { id: 12, name: "MySQL" },
    { id: 13, name: "Database" },
    { id: 14, name: "SQL" },
    { id: 15, name: "Docker" },
    { id: 16, name: "Container" },
    { id: 17, name: "DevOps" },
    { id: 18, name: "MVP" },
    { id: 19, name: "Software Architecture" },
    { id: 20, name: "JWT" },
    { id: 21, name: "Authentication" },
    { id: 22, name: "Security" },
    { id: 23, name: "Bootstrap" },
    { id: 24, name: "Responsive Design" },
    { id: 25, name: "Frontend Framework" },
    { id: 26, name: "Data Exchange" },
    { id: 27, name: "Web Security" },
    { id: 28, name: "SQL Injection" },
    { id: 29, name: "XSS" },

];